In [50]:
import pandas as pd

In [51]:
data0 = pd.read_csv("C:/Users/LENOVO/finalyearproject/dataset/online-valid.csv")
data0.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,6557033,http://u1047531.cp.regruhosting.ru/acces-inges...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T22:01:43+00:00,yes,2020-05-09T22:03:07+00:00,yes,Other
1,6557032,http://hoysalacreations.com/wp-content/plugins...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T22:01:37+00:00,yes,2020-05-09T22:03:07+00:00,yes,Other
2,6557011,http://www.accsystemprblemhelp.site/checkpoint...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T21:54:31+00:00,yes,2020-05-09T21:55:38+00:00,yes,Facebook
3,6557010,http://www.accsystemprblemhelp.site/login_atte...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T21:53:48+00:00,yes,2020-05-09T21:54:34+00:00,yes,Facebook
4,6557009,https://firebasestorage.googleapis.com/v0/b/so...,http://www.phishtank.com/phish_detail.php?phis...,2020-05-09T21:49:27+00:00,yes,2020-05-09T21:51:24+00:00,yes,Microsoft

In [52]:
phishtraining = data0.sample(n = 261, random_state = 12).copy()
phishtraining = phishtraining.reset_index(drop=True)
phishtraining.head()

,phish_id,url,phish_detail_url,submission_time,verified,verification_time,online,target
0,6514946,http://confirmprofileaccount.com/,http://www.phishtank.com/phish_detail.php?phis...,2020-04-19T11:06:55+00:00,yes,2020-04-19T13:42:41+00:00,yes,Other
1,4927651,http://www.marreme.com/MasterAdmin/04mop.html,http://www.phishtank.com/phish_detail.php?phis...,2017-04-04T19:35:54+00:00,yes,2017-05-03T23:00:42+00:00,yes,Other
2,5116976,http://modsecpaststudents.com/review/,http://www.phishtank.com/phish_detail.php?phis...,2017-07-25T18:48:30+00:00,yes,2017-07-28T16:01:36+00:00,yes,Other
3,6356131,https://docs.google.com/forms/d/e/1FAIpQLScL6L...,http://www.phishtank.com/phish_detail.php?phis...,2020-01-13T20:13:37+00:00,yes,2020-01-17T01:55:38+00:00,yes,Other
4,6535965,https://oportunidadedasemana.com/americanas//?...,http://www.phishtank.com/phish_detail.php?phis...,2020-04-29T00:01:03+00:00,yes,2020-05-01T10:55:35+00:00,yes,Other

In [53]:
data1 = pd.read_csv("C:/Users/LENOVO/finalyearproject/dataset/benign.csv")
data1.columns = ['URLs']
data1.head()

                                                URLs
0  http://1337x.to/torrent/1110018/Blackhat-2015-...
1  http://1337x.to/torrent/1122940/Blackhat-2015-...
2  http://1337x.to/torrent/1124395/Fast-and-Furio...
3  http://1337x.to/torrent/1145504/Avengers-Age-o...
4  http://1337x.to/torrent/1160078/Avengers-age-o...

In [54]:
legitraining = data1.sample(n = 261, random_state = 12).copy()
legitraining = legitraining.reset_index(drop=True)
legitraining.head()

                                                URLs
0  http://graphicriver.net/search?date=this-month...
1  http://ecnavi.jp/redirect/?url=http://www.cros...
2  https://hubpages.com/signin?explain=follow+Hub...
3  http://extratorrent.cc/torrent/4190536/AOMEI+B...
4  http://icicibank.com/Personal-Banking/offers/o...

In [55]:
data2 = pd.read_csv("C:/Users/LENOVO/finalyearproject/dataset/p-banklinks.csv")
data2.columns = ['URLs']
data2.head()

                                              URLs
0     www.allianceonlinebankinglogin.page.html.c@m
1  https://www.ambank.secureloginwithusonetime.com
2                wve.login6ankc1mb.c0m.andmalaysia
3         https.click.tosignupwith@us.hlb.com.html
4                  https://192.57.90.0.maybank.com

In [56]:
phishtesting = data2.copy()
phishtesting = data2.sample(n = 39, random_state = 12).copy()
phishtesting = phishtesting.reset_index(drop=True)

In [57]:
data3 = pd.read_csv("C:/Users/LENOVO/finalyearproject/dataset/l-banklinks.csv")
data3.columns = ['URLs']
data3.head()

                                URLs
0  https://www.allianceonline.com.my
1          https://www.ambank.com.my
2            https://www.cimb.com.my
3             https://www.hlb.com.my
4            https://www.maybank.com

In [58]:
legitesting = data3.copy()
legitesting = data3.sample(n = 39, random_state = 12).copy()
legitesting = legitesting.reset_index(drop=True)

features extraction

In [59]:
from urllib.parse import urlparse,urlencode
import ipaddress
import re

In [60]:
def getDomain(url):  
  domain = urlparse(url).netloc
  if re.match(r"^www.",domain):
	       domain = domain.replace("www.","") 
  return domain

In [61]:
def havingIP(url):
  try:
    ipaddress.ip_address(url)
    ip = 1
  except:
    ip = 0
  return ip

In [62]:
def haveAtSign(url):
  if "@" in url:
    at = 1    
  else:
    at = 0    
  return at

In [63]:
def getLength(url):
  if len(url) < 50:
    length = 0            
  else:
    length = 1            
  return length

In [64]:
def getDepth(url):
  s = urlparse(url).path.split('/')
  depth = 0
  for j in range(len(s)):
    if len(s[j]) != 0:
      depth = depth+1
  return depth

In [65]:
def redirection(url):
  pos = url.rfind('//')
  if pos > 6:
    if pos > 7:
      return 1
    else:
      return 0
  else:
    return 0

In [66]:
def httpDomain(url):
  domain = urlparse(url).netloc
  if 'https' in domain:
    return 1
  else:
    return 0

In [67]:
shortening_services = r"bit\.ly|goo\.gl|shorte\.st|go2l\.ink|x\.co|ow\.ly|t\.co|tinyurl|tr\.im|is\.gd|cli\.gs|" \
                      r"yfrog\.com|migre\.me|ff\.im|tiny\.cc|url4\.eu|twit\.ac|su\.pr|twurl\.nl|snipurl\.com|" \
                      r"short\.to|BudURL\.com|ping\.fm|post\.ly|Just\.as|bkite\.com|snipr\.com|fic\.kr|loopt\.us|" \
                      r"doiop\.com|short\.ie|kl\.am|wp\.me|rubyurl\.com|om\.ly|to\.ly|bit\.do|t\.co|lnkd\.in|db\.tt|" \
                      r"qr\.ae|adf\.ly|goo\.gl|bitly\.com|cur\.lv|tinyurl\.com|ow\.ly|bit\.ly|ity\.im|q\.gs|is\.gd|" \
                      r"po\.st|bc\.vc|twitthis\.com|u\.to|j\.mp|buzurl\.com|cutt\.us|u\.bb|yourls\.org|x\.co|" \
                      r"prettylinkpro\.com|scrnch\.me|filoops\.info|vzturl\.com|qr\.net|1url\.com|tweez\.me|v\.gd|" \
                      r"tr\.im|link\.zip\.net"

In [68]:
def tinyURL(url):
    match=re.search(shortening_services,url)
    if match:
        return 1
    else:
        return 0

In [69]:
def prefixSuffix(url):
    if '-' in urlparse(url).netloc:
        return 1            
    else:
        return 0

In [70]:
%pip install python-whois

Requirement already satisfied: python-whois in c:\users\lenovo\anaconda3\lib\site-packages (0.9.5)
Requirement already satisfied: python-dateutil in c:\users\lenovo\anaconda3\lib\site-packages (from python-whois) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\lenovo\anaconda3\lib\site-packages (from python-dateutil->python-whois) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [71]:
from bs4 import BeautifulSoup
import whois
import urllib
import urllib.request
from datetime import datetime

In [72]:
def domainAge(domain_name):
  creation_date = domain_name.creation_date
  expiration_date = domain_name.expiration_date
  if (isinstance(creation_date,str) or isinstance(expiration_date,str)):
    try:
      creation_date = datetime.strptime(creation_date,'%Y-%m-%d')
      expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
    except:
      return 1
  if ((expiration_date is None) or (creation_date is None)):
      return 1
  elif ((type(expiration_date) is list) or (type(creation_date) is list)):
      return 1
  else:
    ageofdomain = abs((expiration_date - creation_date).days)
    if ((ageofdomain/30) < 6):
      age = 1
    else:
      age = 0
  return age

In [73]:
def domainEnd(domain_name):
  expiration_date = domain_name.expiration_date
  if isinstance(expiration_date,str):
    try:
      expiration_date = datetime.strptime(expiration_date,"%Y-%m-%d")
    except:
      return 1
  if (expiration_date is None):
      return 1
  elif (type(expiration_date) is list):
      return 1
  else:
    today = datetime.now()
    end = abs((expiration_date - today).days)
    if ((end/30) < 6):
      end = 0
    else:
      end = 1
  return end

In [74]:
def featureExtraction(url,label):

  features = []
  features.append(getDomain(url))
  features.append(havingIP(url))
  features.append(haveAtSign(url))
  features.append(getLength(url))
  features.append(getDepth(url))
  features.append(redirection(url))
  features.append(httpDomain(url))
  features.append(tinyURL(url))
  features.append(prefixSuffix(url))
  
  dns = 0
  try:
    domain_name = whois.whois(urlparse(url).netloc)
  except:
    dns = 1

  features.append(dns)
  features.append(1 if dns == 1 else domainAge(domain_name))
  features.append(1 if dns == 1 else domainEnd(domain_name))

  features.append(label)
  
  return features

features extraction on training dataset

In [75]:
legitraining.shape

(261, 1)

In [76]:
legi_features_train = []
label = 0

for url in legitraining['URLs']:
  legi_features_train.append(featureExtraction(url,label))

2025-06-09 19:22:36,442 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:23:02,736 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:23:44,901 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:24:21,558 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:24:28,987 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:24:48,392 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:25:07,158 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:25:15,620 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it
2025-06-09 19:28:05,174 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out
2025-06-09 19:28:15,161 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:29:41,554 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:29:48,057 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:30:40,006 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it

In [77]:
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection', 'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Domain_Age', 'Domain_End', 'label']

legitimatetrain = pd.DataFrame(legi_features_train, columns= feature_names)
legitimatetrain.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
0,graphicriver.net,0,0,1,1,0,0,0,0,0,1,1,0
1,ecnavi.jp,0,0,1,1,1,0,0,0,0,0,1,0
2,hubpages.com,0,0,1,1,0,0,0,0,0,0,1,0
3,extratorrent.cc,0,0,1,3,0,0,0,0,0,0,1,0
4,icicibank.com,0,0,1,3,0,0,0,0,0,0,1,0

In [78]:
legitimatetrain.to_csv("C:/Users/LENOVO/finalyearproject/dataset/legitimatetrain.csv", index= False)

In [79]:
phishtraining.shape

(261, 8)

In [80]:
phish_features_train = []
label = 1

for url in phishtraining['url']:
  phish_features_train.append(featureExtraction(url,label))

2025-06-09 19:33:20,723 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out
2025-06-09 19:33:53,048 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed
2025-06-09 19:34:49,462 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [WinError 10061] No connection could be made because the target machine actively refused it
2025-06-09 19:35:40,463 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out
2025-06-09 19:36:07,445 - whois.whois - ERROR - Error trying to connect to socket: closing socket - timed out
2025-06-09 19:38:56,565 - whois.whois - ERROR - Error trying to connect to socket: closing socket - [Errno 11001] getaddrinfo failed

In [81]:
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection', 'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Domain_Age', 'Domain_End', 'label']

phishingtrain = pd.DataFrame(phish_features_train, columns= feature_names)
phishingtrain.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
0,confirmprofileaccount.com,0,0,0,0,0,0,1,0,1,1,1,1
1,marreme.com,0,0,0,2,0,0,0,0,0,0,0,1
2,modsecpaststudents.com,0,0,0,1,0,0,0,0,0,1,1,1
3,docs.google.com,0,0,1,5,0,0,0,0,0,1,1,1
4,oportunidadedasemana.com,0,0,1,1,1,0,0,0,1,1,1,1

In [82]:
phishingtrain.to_csv("C:/Users/LENOVO/finalyearproject/dataset/phishingtrain.csv", index= False)

In [83]:
trainingdata = pd.concat([legitimatetrain, phishingtrain]).reset_index(drop=True)
trainingdata.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
0,graphicriver.net,0,0,1,1,0,0,0,0,0,1,1,0
1,ecnavi.jp,0,0,1,1,1,0,0,0,0,0,1,0
2,hubpages.com,0,0,1,1,0,0,0,0,0,0,1,0
3,extratorrent.cc,0,0,1,3,0,0,0,0,0,0,1,0
4,icicibank.com,0,0,1,3,0,0,0,0,0,0,1,0

In [84]:
trainingdata.tail()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
517,mms.tucsonhispanicchamber.net,0,0,1,1,0,0,0,0,0,0,1,1
518,nonaisazeh.com,0,0,0,1,0,0,0,0,1,1,1,1
519,sattvagroupexotic.in,0,0,0,1,0,0,0,0,0,1,1,1
520,atagucsea.com,0,0,1,5,0,0,0,0,0,0,0,1
521,steampoweroesd.me,0,0,0,1,0,0,0,0,0,1,1,1

In [85]:
trainingdata.shape

(522, 13)

In [86]:
trainingdata.to_csv("C:/Users/LENOVO/finalyearproject/dataset/trainingdata.csv", index=False)

features extraction on testing dataset

In [87]:
legitesting.shape

(39, 1)

In [88]:
legi_features_test = []
label = 0

for url in legitesting['URLs']:
  legi_features_test.append(featureExtraction(url,label))

In [89]:
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection', 'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Domain_Age', 'Domain_End', 'label']

legitimatetest = pd.DataFrame(legi_features_test, columns= feature_names)
legitimatetest.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
0,,0,0,0,1,0,0,0,0,0,1,1,0
1,,0,0,0,1,0,0,0,0,0,1,1,0
2,,0,0,0,1,0,0,0,0,0,1,1,0
3,,0,0,0,4,0,0,0,0,0,1,1,0
4,,0,0,0,3,0,0,0,0,0,1,1,0

In [90]:
legitimatetest.to_csv("C:/Users/LENOVO/finalyearproject/dataset/legitimatetest.csv", index= False)

In [91]:
phishtesting.shape

(39, 1)

In [92]:
phish_features_test = []
label = 1

for url in phishtesting['URLs']:
  phish_features_test.append(featureExtraction(url,label))

In [93]:
feature_names = ['Domain', 'Have_IP', 'Have_At', 'URL_Length', 'URL_Depth','Redirection', 'https_Domain', 'TinyURL', 'Prefix/Suffix', 'DNS_Record', 'Domain_Age', 'Domain_End', 'label']

phishingtest = pd.DataFrame(phish_features_test, columns= feature_names)
phishingtest.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
0,,0,0,0,1,0,0,0,0,0,1,1,1
1,,0,1,0,1,0,0,0,0,0,1,1,1
2,,0,0,0,1,0,0,0,0,0,1,1,1
3,,0,0,0,1,0,0,0,0,0,1,1,1
4,,0,1,0,2,0,0,0,0,0,1,1,1

In [94]:
phishingtest.to_csv("C:/Users/LENOVO/finalyearproject/dataset/phishingtest.csv", index= False)

In [95]:
testingdata = pd.concat([legitimatetest, phishingtest]).reset_index(drop=True)
testingdata.head()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
0,,0,0,0,1,0,0,0,0,0,1,1,0
1,,0,0,0,1,0,0,0,0,0,1,1,0
2,,0,0,0,1,0,0,0,0,0,1,1,0
3,,0,0,0,4,0,0,0,0,0,1,1,0
4,,0,0,0,3,0,0,0,0,0,1,1,0

In [96]:
testingdata.tail()

,Domain,Have_IP,Have_At,URL_Length,URL_Depth,Redirection,https_Domain,TinyURL,Prefix/Suffix,DNS_Record,Domain_Age,Domain_End,label
73,,0,1,0,1,0,0,0,0,0,1,1,1
74,,0,0,0,1,0,0,0,0,0,1,1,1
75,,0,0,0,1,1,0,0,0,0,1,1,1
76,,0,1,0,2,0,0,0,0,0,1,1,1
77,,0,0,0,3,0,0,0,0,0,1,1,1

In [97]:
testingdata.shape

(78, 13)

In [98]:
testingdata.to_csv("C:/Users/LENOVO/finalyearproject/dataset/testingdata.csv", index=False)